const devQuotes: string[] = [
    "Code is like humor. When you have to explain it, it’s bad.",
    "In programming, the hard part isn’t solving problems, but deciding what problems to solve.",
    "Programs must be written for people to read, and only incidentally for machines to execute.",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    "First, solve the problem. Then, write the code.",
    "Programming isn’t about what you know; it’s about what you can figure out.",
    "The best error message is the one that never shows up.",
    "One of my most productive days was throwing away 1,000 lines of code.",
    "The best way to get a project done faster is to start sooner.",
    "Good code is its own best documentation.",
    "Code never lies, comments sometimes do.",
    "It’s not a bug; it’s an undocumented feature.",
    "The best code is no code at all.",
    "Simplicity is the soul of efficiency.",
    "A good programmer is someone who always looks both ways before crossing a one-way street.",
    "The most important property of a program is whether it accomplishes the intention of its user.",
    "Talk is cheap. Show me the code.",
    "If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
    "Before software can be reusable it first has to be usable.",
    "The function of good software is to make the complex appear simple.",
    "Walking on water and developing software from a specification are easy if both are frozen.",
    "Programming can be fun, so can cryptography; however, they should not be combined.",
    "There are only two kinds of programming languages: those people always complain about and those nobody uses.",
    "Java is to JavaScript what car is to carpet.",
    "Don’t comment bad code—rewrite it.",
    "Copy-and-paste was a design error.",
    "The best performance improvement is the transition from the nonworking state to the working state.",
    "The computer was born to solve problems that did not exist before.",
    "If you think it’s simple, then you have misunderstood the problem.",
    "Simplicity is prerequisite for reliability.",
    "Code is the interface between human and machine understanding.",
    "A language that doesn’t affect the way you think about programming is not worth knowing.",
    "A clever person solves a problem. A wise person avoids it.",
    "There is nothing quite so permanent as a quick fix.",
    "Premature optimization is the root of all evil.",
    "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to produce bigger and better idiots. So far, the universe is winning.",
    "Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.",
    "When I wrote this code, only God and I understood what I did. Now only God knows.",
    "The trouble with programmers is that you can never tell what a programmer is doing until it’s too late.",
    "It works on my machine.",
    "The best way to predict the future is to invent it.",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit.",
    "Programming is like writing a book... except if you miss out a single comma on page 126, the whole thing makes no sense.",
    "In theory, there is no difference between theory and practice. But, in practice, there is.",
    "Software is like entropy: It is difficult to grasp, weighs nothing, and obeys the Second Law of Thermodynamics; i.e., it always increases.",
    "There are two ways of constructing a software design: one way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies.",
    "Debugging is like being the detective in a crime movie where you are also the murderer.",
    "In software development, the only constant is change.",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity."
  ];

  export default devQuotes;
  